### ISSUE TITLE
Video Output Low

### ISSUE THREAD

**Issue by dropitlikecross** [torch2424/live-stream-radio#113]
So after spending a few hours playing with settings I can't seem to good video output. 796Kbps seems to be the highest I can get.

I'm running this on an azure cloud and I've tried different machines to see if it was a hardware issue, the most powerful one being:

2 VCPUS
7 GB RAM
8 Data Disks
6400 MAX IOPS

Youtube error:
```
12:16 PM Bad Video output low
YouTube is not receiving enough video to maintain smooth streaming. As such, viewers will experience buffering.
The stream's current bitrate (796.00 Kbps) is lower than the recommended bitrate. We recommend that you use a stream bitrate of 2500 Kbps.
```

FFMPEG:
```
ffmpeg version 4.1-1~18.04.york1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version='1~18.04.york1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-nonfree --enable-libfdk-aac --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared

```

Config.json

Default settings except changing it to 720

```
  "video_height": "720",
  "video_width": "1280,
  "video_bit_rate": "250K",

```

Things I've tried;

- Increase buffer size
- Remove buffer size
- Increase video bit rate
- Increase and reduce CFR
- Remove CFR
- Reduce threads
- Remove threads

Any help would be appreciated.

**Comment by torch2424** [comment]
Yeah I've been having this same problem, and documented at #105 . I've tried all the things above as well. I've found it to be real hit or miss, depending on the device / platform. If you have any ideas, it would be much appreciated. PRs to for any fixes are greatly appreciated for this 😄

**Comment by dropitlikecross** [comment]
@torch2424 ffmpeg does have a CBR value that you can input.

**Comment by dropitlikecross** [comment]
So on the same machine, with an older revision off ffmpeg I ran into a similar issue but running 4.1  this works without issue. 

Is there an easy way to add the extra settings into the script to test?

```
FFMPEG=ffmpeg
GIF=random.gif
STREAM_KEY=meow
TEXT=current_song.txt
COLOR="0xFFFFFF"
BCOLOR="0x000000"
INRES=1366x768 # input resolution
OUTRES=1920x1080 # output resolution
FPS=15 # target FPS
GOP=30 # i-frame interval, should be double of FPS,
GOPMIN=15 # min i-frame interval, should be equal to fps,
THREADS=4 # max 6
CBR=2500k # constant bitrate (should be between 1000k - 3000k)
QUALITY=veryfast # one of the many FFMPEG preset
AUDIO_RATE=44100
KEYINT=$(expr $FPS \* 3)

$FFMPEG -thread_queue_size 1024 -f alsa -ac 2 -i hw:Loopback,1,0 -fflags +genpts -ignore_loop 0 -r $FPS -i $GIF \
-vf drawtext="fontfile=/usr/share/fonts/truetype/slant.ttf:bordercolor=$BCOLOR: borderw=1: fontcolor=$COLOR:textfile=$TEXT:reload=1:y=10:x=5:fontsize=38" \
-vcodec libx264 -x264opts keyint=$KEYINT:min-keyint=$KEYINT:scenecut=-1 -b:v $CBR -minrate $CBR -maxrate $CBR -pix_fmt yuv420p \
-s $OUTRES -preset $QUALITY -acodec aac -threads $THREADS -fflags nobuffer \
-bufsize $CBR -f flv "rtmp://a.rtmp.youtube.com/live2/$STREAM_KEY" \

2> log_stream.txt

```

**Comment by torch2424** [comment]
Yeah definitely, feel free to fork the project, and open a PR with those extra settings you want to add 😄 

I tried this same route of using FFMPEG directly, but I just couldn't get it still. Stoked you figured this out! 😄 

cc @AndreasWebdev If you have time, you may be interested in this as well 🎉

**Comment by torch2424** [comment]
Let me know if you want to open a PR. I'm excited to try this myself. I'll try and report back with my findings later today

**Comment by torch2424** [comment]
So This will be a bit of a long response:


# Your configuration

> So on the same machine, with an older revision off ffmpeg I ran into a similar issue but running 4.1 this works without issue. (This is using the raspberrypi guide as a base :P )

> Is there an easy way to add the extra settings into the script to test?

So after looking at your command, it doesn't have any parameters that aren't already exposed in the config. If you look through `src/stream/stream.js` you will see every command is there (where some are done by assuming from another).

# Some additional research done by me

So I went ahead and dug around twitch inspector (BTW, don't do bandwidthtest=true, will omit a lot of the info outside of the bitrate). And here is the current master:

<img width="982" alt="screen shot 2019-02-13 at 8 57 00 pm" src="https://user-images.githubusercontent.com/1448289/52764940-e996ed00-2fd6-11e9-89b0-0f9768e0d772.png">

As you can see above, this has a very varying bit rate. Thus after adding some of the flags you suggested (but don't require any config changes), things look a bit more stable:

<img width="1280" alt="screen shot 2019-02-13 at 8 52 00 pm" src="https://user-images.githubusercontent.com/1448289/52764968-0b906f80-2fd7-11e9-87e4-a4456de31315.png">
<img width="316" alt="screen shot 2019-02-13 at 8 52 06 pm" src="https://user-images.githubusercontent.com/1448289/52764969-0b906f80-2fd7-11e9-9cf1-2b22ec0b3d64.png">
<img width="331" alt="screen shot 2019-02-13 at 8 52 20 pm" src="https://user-images.githubusercontent.com/1448289/52764970-0b906f80-2fd7-11e9-8640-1f5706762d1d.png">

Thus framerate and bitrate look pretty stable and constant. And as you can see twitch has absolutely no problems with the stream. And all the settings are really close (if not exact), to recommended settings that streaming sites reccomened (linked below).

However, I couldn't get it to reappear, but I was testing youtube and it particularly called out this general thing: "Hey, your bitrate is (606)Kbps. You should use the reccomended bit rate of 2500Kbps". Which made me think, okay cool, let's look at that.

So now I've updated the default config to [Twitch's minimum 720p@30fps](https://stream.twitch.tv/encoding/), which is also matches [Youtube's minimum 720p@30fps](https://support.google.com/youtube/answer/2853702?hl=en). Which means the bit rate is increased by a lot. Which may fix a lot of issues on the youtube end, [as youtube seems particular about the video size / bitrate combination].

After this, twitch inspector gives us:

<img width="998" alt="screen shot 2019-02-13 at 10 21 37 pm" src="https://user-images.githubusercontent.com/1448289/52766979-d63b5000-2fdd-11e9-8838-c9777f8becea.png">
<img width="330" alt="screen shot 2019-02-13 at 10 22 05 pm" src="https://user-images.githubusercontent.com/1448289/52766980-d63b5000-2fdd-11e9-8b75-6dcde1c16c64.png">

Which is more of what we want to see I guess? 🤔 

# Video Output Low

So I went ahead and did some research on [my personal stream](https://www.youtube.com/channel/UCWApVYrXzetXXaR4Ef4zn5w/live). Which might I say, only ever really needs to restart about once a week (because Youtube kills the stream). Seems like I only really ever get the "Video output low", whenever the song changes and the stream goes down for the half of a second:

<img width="428" alt="screen shot 2019-02-13 at 9 21 02 pm" src="https://user-images.githubusercontent.com/1448289/52765146-cc165300-2fd7-11e9-9237-c45506a740f0.png">

Thus, this is by design of the stream. Ideally, this wouldn't hapeen, and hopefully we can find a solution to have another ffmpeg process that takes in video from the main ffmpeg process, and overlays it over a black image or soemthing, that way the stream truly never goes down. But that would be at the expense of more performance :p Thus, I opened #114

**Comment by dropitlikecross** [comment]
@torch2424 Thank you very much for spending the time testing.
 Could you post your modified config file? I'd like to run a direct comparison on azure and see what I get.

**Comment by torch2424** [comment]
@dropitlikecross Sure, it's in the PR I linked, but here is the exact file: https://github.com/torch2424/live-stream-radio/blob/52c224caeb7995deebd1dd05eb76ab14d1a9190a/src/generate/template/config.json
