### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by AndreasWebdev** [torch2424/live-stream-radio#45]
I thought it would make sense to start an issue for initial windows support for the node-rebuild! I'll be testing the newest code once I am home and report back here. For now, here are some problems I noticed when trying it out a few days ago.

**User-friendly installation**
@torch2424 you once said you want to make the installation to be as easy as possible. On windows, you currently have to download a precompiled build, put it somewhere and then change your system variables to add this folder to your path. At one point you bundled a build of ffmpeg in the project, why did you decide against it? How do you think we could make this as easy as possible for users?

**Paths in the config.json**
Appearently, paths work weird on windows. The default config uses "./folder" syntax for paths, however this yields "directory not found". You have to manually edit the paths to "/folder" if you want a quick fix. Is there maybe a module to dynamically construct these paths? Or maybe something built in so that the config can use ./ and still work on windows? this way the config-file is not plattform-dependent.

**Comment by AndreasWebdev** [comment]
@torch2424 maybe you could add a node-rebuild label or something so the issues-list stays readable with two current versions in development

**Comment by torch2424** [comment]
Awesome! Thanks for opening this.

So to be honest, I don't have any windows dev environments. I only have a PC I rarely use for gaming. So if you would be willing to drive this that would be awesome 👍 

So in terms of making it easy for install, I actually already implemented this the other day! You can pass an FFMPEG Binary through the config, so you can place the executable wherever you would like, and it will just use that instead 😄 

In terms of no longer offering builds, I did it mostly thinking about supporting multiple patforms. Ffmpeg binaries bloats the repo size by a lot, and I don't want it to become too large. Also, building/keeping FFMPEG up to date for our builds for every platform would be quite a challenge.

Handling different path types will definitely be quite the challenge. If you would be so kind, feel free to open a pr for a `live-stream-radio --generate --windows` flag, to make some modifications to the config.json on generating.


And since it seems to just be us three talking about the rebuild, I'll hold off on making a new label, I was actually going to just close all the no longer relevant old ones haha!

**Comment by torch2424** [comment]
So I closed all issues, going to push up version 2.0.0 soon that way we are all on the same page haha!

**Comment by AndreasWebdev** [comment]
I have worked on the generate function so that it rewrites the paths automatically, however as I haven't created a branch for #52 I need to wait until this gets merged until I can start a new PR with the changes.

**Comment by torch2424** [comment]
Rad. Left a review on the docs update, and then we can pull that in and get windows going 😄

**Comment by AndreasWebdev** [comment]
Closed as #56 is not applicable.
