### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AndreasWebdev** [torch2424/live-stream-radio#49]
Hey @torch2424 just letting you know that I forked the documentation and currently rewrite the content of the readme, create some boilerplate pages and write-up a detailled but easy getting-started tutorial! I will probably push a PR later this day!

**Comment by torch2424** [comment]
Oh nice! Actually... I also just finished writing docs in #50 , I'm sorry if any of it is similar to what you did 😢 

That being said, feel free to move anything your wrote into what I wrote, would gladly pull it in, cause I wrote all of this kinda fast in order to say that I'm "done" with version 2.0 😄 Gonna go and update my stream now with all the new changes haha!

**Comment by AndreasWebdev** [comment]
I am currently re-forking the project and implement my local changes! Thank god you went more into detail with the APi than the CLI as finished about the same time you pushed #50 with a nice rewrite for the installation.

**Comment by AndreasWebdev** [comment]
There is now a PR on #52

**Comment by torch2424** [comment]
Awesome! Left a review there 😄
